channels:
- conda-forge
dependencies:
- attrs
- black = 22.3.0
- bottleneck
- click
- dask
- flake8
- flox
- fsspec
- isort
- make
- mdformat
- mypy
- nomkl
- numexpr
- numpy >= 1.22.0
- pip
- pytest
- pytest-cov
- rasterio >= 1.2.4
- rioxarray
- scipy
- typer
- types-setuptools
- xarray-sentinel >= 0.9.0
- xmlschema
- zarr
- pip:
  - mdformat-gfm
  - git+https://github.com/pydata/xarray.git
