channels:
- conda-forge
dependencies:
- attrs
- bottleneck
- click
- dask >= 2022.6.1
- flox
- fsspec
- gdal
- make
- mdformat
- mypy
- numexpr
- numpy >= 1.22.0
- pip
- pytest
- pytest-cov
- rasterio >= 1.3.0
- rioxarray
- scipy
- typer
- types-setuptools
- xarray >= 2022.06.0
- xarray-sentinel >= 0.9.2
- xmlschema
- pip:
  - mdformat-gfm
