channels:
  - conda-forge
dependencies:
  - attrs
  - black = 22.3.0
  - click
  - dask
  - flake8
  - fsspec
  - isort
  - make
  - mdformat
  - mypy
  - nomkl
  - numpy >= 1.22.0
  - pip
  - pytest
  - pytest-cov
  - rasterio >= 1.2.4
  - rioxarray
  - scipy
  - types-setuptools
  - xarray >= 0.20.2
  - xarray-sentinel
  - xmlschema
  - zarr
  - pip:
      - mdformat-gfm
