name: on-push

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ubuntu-latest-3.9
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ubuntu-latest-3.9
        auto-update-conda: false
        python-version: 3.9
        use-only-tar-bz2: true
    - name: Install dependencies
      run: |
        make conda-env-update ENVIRONMENT=ubuntu-latest-3.9
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Run unit tests
      run: |
        make test COV_REPORT=xml
    - name: Upload code coverage to Codecov
      uses: codecov/codecov-action@v1

  code-quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2
    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key:
          ubuntu-latest-3.9
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: ubuntu-latest-3.9
        auto-update-conda: false
        python-version: 3.9
        use-only-tar-bz2: true
    - name: Install dependencies
      run: |
        make conda-env-update ENVIRONMENT=ubuntu-latest-3.9
    - name: Install package
      run: |
        python -m pip install --no-deps -e .
    - name: Run code quality tests
      run: |
        make code-quality

  code-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check code style with black
      run: |
        $CONDA/bin/conda install black
        $CONDA/bin/black --check .
    - name: Check code style with isort
      run: |
        $CONDA/bin/conda install isort
        $CONDA/bin/isort --check .
    - name: Check documentation style with mdformat
      run: |
        $CONDA/bin/conda install -c conda-forge mdformat
        $CONDA/bin/mdformat --check .

  distribution:
    runs-on: ubuntu-latest
    needs: [unit-tests, code-quality, code-style]

    steps:
    - uses: actions/checkout@v2
    - name: Build distributions
      run: |
        $CONDA/bin/python -m pip install build
        $CONDA/bin/python -m build
    - name: Publish a Python distribution to PyPI
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}